[package]
name = "vector-database"
version = "0.1.0"
edition = "2021"

[dependencies]
langchain-rust = { version = "4.3.0", features = ["qdrant", "ollama"] }
qdrant-client = "= 1.8.0"
serde_json = "1.0.122"
